### ISSUE TITLE
llamas

### ISSUE THREAD

**Issue by dieseltravis** [whyaz/whyaz#27]
add some llamas

**Comment by lynnandtonic** [comment]
Best issue ever.

**Comment by rtorr** [comment]
:+1:

**Comment by ncrohn** [comment]
![llama llama llama llama llama](http://d24w6bsrhbeh9d.cloudfront.net/photo/aKz1ppZ_460sa.gif)

**Comment by dieseltravis** [comment]
Well in between other work-related bugs, I spent a few minutes trying to combine the `.heart` and the `.bridge` into this: http://jsbin.com/tayeya/2/

Does that look like a larger white llama standing in front of a smaller black llama? I think they need ears or something.

(feel free to close)

**Comment by lynnandtonic** [comment]
Nice, @dieseltravis! I'm trying to think of how we can incorporate the llamas somehow. Maybe a "Memes you love" section. Since Grumpy Cat is also from AZ?

Not sure if too silly, but definitely fun. :)

**Comment by lynnandtonic** [comment]
Took over a year, but the llamas are on the site now. :)

![image](https://cloud.githubusercontent.com/assets/871315/15021494/09782cd6-11dc-11e6-9fec-554579811eee.png)

**Comment by dieseltravis** [comment]
haha, great work!
