### ISSUE TITLE
Move the site onto GitHub Pages

### ISSUE THREAD

**Issue by lynnandtonic** [whyaz/whyaz#30]
We're going to make the site fully static and move it onto GitHub Pages. Here are the steps needed to do that (not necessarily in order):

- [x] Move repo to WhyAZ org -- @lynnandtonic and @kennedyj
- [x] Make the site static -- @ncrohn or @jacobheun 
- [x] Change form to Wufoo (or some other) form -- @lynnandtonic
- [x] Figure out static contributors list that compiles during a build step (or remove it altogether) -- @ncrohn or @jacobheun 
- [x] Create whyaz.github.io in WhyAZ org and put something there -- @lynnandtonic
- [x] Update DNS -- @kennedyj 
- [x] Delete site from CloudFront -- @kennedyj 
- [x] Update all links to point to the new org and repo -- @lynnandtonic

**Comment by ncrohn** [comment]
#32 takes care of the static conversion.
