### ISSUE TITLE
Contributors list not updating

### ISSUE THREAD

**Issue by lynnandtonic** [whyaz/whyaz#42]
Just merged a change from @jasonrose and he wasn't added to the contributors list.

**Comment by lynnandtonic** [comment]
Might be a cache issue. We'll wait and see.

**Comment by jasonrose** [comment]
https://developer.github.com/v3/repos/#list-contributors

```
Contributors data is cached for performance reasons. This endpoint may return information that is a few hours old.
```

**Comment by rtorr** [comment]
@lynnandtonic seems like this should be closed now.

**Comment by lynnandtonic** [comment]
Thanks, guys!
