### ISSUE TITLE
Subset typekit fonts

### ISSUE THREAD

**Issue by jasonrose** [whyaz/whyaz#44]
The fonts why.az uses are 113kb, which is something like 4x the rest of the page content combined; do tisa-sans-web-pro and tisa-web-pro support subsetting to latin?  This might reduce filesize by 75%, depending on how many glyphs there are in the font now.

https://helpx.adobe.com/typekit/using/language-support-subsetting.html

**Comment by lynnandtonic** [comment]
I subset tisa-web-pro for English and removed bold and bold italic support for now. We're not using them and can add them later if we need to.

I also removed tisa-sans-web and replaced it with Verdana.

Thanks, @jasonrose!
